---
title: site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
url: flatfiles
cours:
  output: true
  permalink: Cours/:path/
